version: '3.8'

services:
  api:
    build: .
    container_name: question-extractor-api
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./prompts:/app/prompts
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped